import AnimatedSpeedometer from './AnimatedSpeedometer'
export default AnimatedSpeedometer
export { default as Arc } from './Arc'
export { default as Background } from './Background'
export { default as DangerPath } from './DangerPath'
export { default as Indicator } from './Indicator'
export { default as Marks } from './Marks'
export { default as Needle } from './Needle'
export { default as Progress } from './Progress'
export { default as SpeedometerContext } from './context'